// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type User struct {
	// 主键ID
	ID int32
	// 创建时间
	CreateTime time.Time
	// 更新时间
	UpdateTime time.Time
	// 用户名
	UserName string
}
